spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    #show-sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.engine.internal: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

